name: Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: build with pyinstaller
      run: |
        pyinstaller -i logo.ico -w -F CDI_dice.py 
        pyinstaller -i logo.ico -w CDI_dice.py
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: CDI_Help
        # Directory containing files to upload
        path: .
    - name: Github Release
      uses: elgohr/Github-Release-Action@v3.1
      with:
        # The name of the release to publish
        release: CDI_Help
